# Generated by Django 4.2.3 on 2023-09-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
