# Generated by Django 5.0.3 on 2024-03-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_invoiceproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='quantity',
        ),
    ]
