# Generated by Django 5.0.3 on 2024-03-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_invoiceproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='name',
            field=models.CharField(default='Brownie', max_length=100),
            preserve_default=False,
        ),
    ]
