services:
  - name: web
    env: python=3.9
    buildCommand: |
      pip install -r cafeOrdering/requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    automaticDeploy:
      branchPattern: main
