# Generated by Django 5.0.3 on 2024-03-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='problem_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='resolution_message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
