# Generated by Django 4.2.3 on 2024-02-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reported_problem',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
