# Generated by Django 5.0.3 on 2024-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_problem_resolved_order_resolution_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='problem_order',
            field=models.BooleanField(default=False),
        ),
    ]
