# Generated by Django 4.2.3 on 2024-03-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_reported_problem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_id',
        ),
    ]
