# Generated by Django 5.0.3 on 2024-03-18 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_workspace', models.BooleanField(default=False, verbose_name='Workspace')),
                ('address_line1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2')),
                ('address_line3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 3')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('invoice_business', models.CharField(max_length=100, verbose_name='Business Name')),
                ('invoice_address_line1', models.CharField(max_length=100, verbose_name='Invoice Address Line 1')),
                ('invoice_address_line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Address Line 2')),
                ('invoice_address_line3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Address Line 3')),
                ('invoice_postcode', models.CharField(max_length=100, verbose_name='Invoice Postcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
