# Generated by Django 5.0.3 on 2024-03-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invoice_email',
            field=models.EmailField(default='felix.voyle@icloud.com', max_length=254),
            preserve_default=False,
        ),
    ]
