# Generated by Django 4.2.3 on 2024-02-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line1',
            field=models.CharField(default='123 tester road', max_length=100, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 3'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_workspace',
            field=models.BooleanField(default=False, verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(default='TE5 7ER', max_length=10, verbose_name='Postcode'),
            preserve_default=False,
        ),
    ]
