# Generated by Django 5.0.3 on 2024-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invoice_address_line1',
            field=models.CharField(default='123 Invoice Tester', max_length=100, verbose_name='Invoice Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_address_line2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Address Line 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_address_line3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Address Line 3'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_business',
            field=models.CharField(default='Test Business LTD', max_length=100, verbose_name='Business Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_postcode',
            field=models.CharField(default='TE5 7ER', max_length=100, verbose_name='Invoice Postcode'),
            preserve_default=False,
        ),
    ]
