# Generated by Django 5.0.3 on 2024-03-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(max_length=5, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_sent_date', models.DateField(auto_now_add=True)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
