# Generated by Django 5.0.3 on 2024-03-18 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
